version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:45"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
      include: scope

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:55"
      timezone: "UTC"
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: "chore(docker)"
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: "chore(ci)"
      include: scope
