name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: 'Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'CI/CD'
    labels:
      - 'ci'
      - 'cd'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'dependencies'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No user-facing changes in this release.'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'chore'
      - 'dependencies'
  default: patch

template: |
  ## What's Changed

  $CHANGES
